apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cinema-microservice-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/abbashussainz/multi-region-k8s-deployment
    targetRevision: main
    path: k8s-manifest/microservices
  destination:
    server: https://ad30ed336031840b382a836b7cc2508b-8dfeae18ea704734.elb.us-east-1.amazonaws.com:5443
    namespace: cinema-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true