apiVersion: v1
kind: Service
metadata:
  name: movies
  namespace: cinema-production
spec:
  selector:
    app: movies
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000



# Connect to primary node
