apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: website
  namespace: cinema-production
spec:
  replicas: 1
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: ghcr.io/mmorejon/cinema-website:v2.2.2
          args:
            - "-usersAPI"
            - "http://users:4000/api/users/"
            - "-moviesAPI"
            - "http://movies:4000/api/movies/"
            - "-showtimesAPI"
            - "http://showtimes:4000/api/showtimes/"
            - "-bookingsAPI"
            - "http://bookings:4000/api/bookings/"
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"